export const FETCH_CANDIDATES = "FETCH_CANDIDATES";
export const FETCH_CANDIDATES_SUCCESS = "FETCH_CANDIDATES_SUCCESS";
export const FETCH_CANDIDATES_ERROR = "FETCH_CANDIDATES_ERROR";
export const SEARCH_CANDIDATES_BY_QUERY = "SEARCH_CANDIDATES_BY_QUERY";
export const UPDATE_CANDIDATES = "UPDATE_CANDIDATES"